### ISSUE TITLE
https://en.wikipedia.org/wiki/Coupling_(computer_programming)

### ISSUE THREAD

**Issue by rosscdh** [Galeria-Kaufhof/ets-poms#15]
hmm this doesn't seem too loosely coupled?

**Comment by rosscdh** [comment]
sharing resources in a microservice architecture (even in a SOA model) like this is a recipe for disaster. 

Java can best be done via assembly and dependency or perhaps maven-remote-resources-plugin al la https://blog.sonatype.com/2008/04/how-to-share-resources-across-projects-in-maven/
https://stackoverflow.com/questions/27865238/parent-pom-and-microservices/27878112#27878112

"
Here there is one issue with dependency and dependency management. Say one of your micro service wants to upgrade to newer version of common for some reason...you cant do that as you have parent. I do understand temptation of reducing duplication of redundant things like plugin configuration. In micro service we need to think more about independence of each service.
"

**Comment by ghost** [comment]
Hi @rosscdh - did you read our introduction documentation? 

You can find it at http://tech.kaufhof.io/ets-documentation/Using-ETS/introduction/ 
We are currently working in a 0.x.x version, so many things are missing yet, but the introduction should explain the core ideas.

Does that clarify the intention of the POMs project for you?

**Comment by rosscdh** [comment]
Hey there. Thanks for the quick response. Just read the docs you provided. Which seem to make promises and grand sounding statements but, sorry It feels a little like throwing the baby out with the bathwater.

 In the sense that in today's world of loosely coupled services the last thing you would want is something that tightly couples dependencies creating a dependency monolith.

I guess it comes down to what you are building but I'm not sure I would buy into this particular strategy (if u have an eco system of services, u don't apply pressure to a primary constraint. As this would slow output for all teams and services) as I've seen it before and it creates months of technical dept to be repaid. Guaranteeing conflict free dependency resolution is usually left to each service as it stands and not any kind of strict control system. Otherwise systems can't evolve independently (which is the high and grand point of soa or microservices architecture).

If be interested in knowing more about the context and why it is felt that this approach and constraint of services development teams is needed? (Feels as tho teams are not trusted and dependencies are a huge task?)

From the rest of the docs you are setting standards for internal development of modules which is good but honestly:

```
While this limits your freedom in terms of code base structure, tool choice, dependency management and library choice a bit, this is actually key to reducing errors and increasing productivity, by reducing yak shaving when starting off, and offering guard rails down the road.
```

Thats allot of limitation for many tradeoffs (are there really that many blocker issues in dependency management, that you would create a control project limiting the articulation of all teams?

**Comment by manuelkiessling** [comment]
Closing this as we would like to use Gitter for high-level discussions instead of GitHub issues. I'll join the discussion at https://gitter.im/Galeria-Kaufhof/ETS.
